# Generated by Django 5.1.2 on 2024-10-31 12:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Resource", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MDemo",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "create_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="更新时间"),
                ),
                (
                    "identifier",
                    models.UUIDField(
                        default=uuid.uuid4,
                        null=True,
                        unique=True,
                        verbose_name="唯一标识",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        blank=True, default=False, null=True, verbose_name="是否启用"
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        blank=True, default="", null=True, verbose_name="文本"
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_images",
                        to="Resource.mimage",
                        verbose_name="图片",
                    ),
                ),
            ],
            options={
                "verbose_name": "样例",
                "verbose_name_plural": "样例",
            },
        ),
    ]
